package ui;


import java.util.ArrayList;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Processo;
import util.Temp;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jeison.marques
 */
public class ProcessamentoUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProcessamentoUI
     */
    private Timer timer;
    public ArrayList<Processo> listRun = new ArrayList();
    
    public ProcessamentoUI() {
        initComponents();
        timer = new Timer();
    
     timer.scheduleAtFixedRate(new TimerTask() {
     public void run() {
            try {             
                VerificaProcessoNovo();
                AtualizaListas();
                ProcessoFifo();
            } catch (InterruptedException ex) {
                Logger.getLogger(ProcessamentoUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Date d = new Date();
            System.out.println("Processando as " + d.toString());
            System.out.println("Lista de Processamento: "+listRun.size());
            System.out.println("Lista de Processos: "+Temp.list.size());
            }
        }, 0, 1000);
    }
    
    public void ProcessoFifo() throws InterruptedException
    {
        if(listRun.size() > 0)
        {
            
            Processo proc = listRun.get(0);
            Processo procTemp = Temp.ReturnaProcessoPorPid(proc.getPid());
            TrocaEstado(procTemp, "Execucao");      
            listRun.remove(0);
                      
            if("CPU-Bound".equals(proc.getTipo()))
            {
                Thread.sleep(700);
                proc.setProcessado(true);
            }
            if("I/O-Bound(Disco)".equals(proc.getTipo()))
            {
                Thread.sleep(500);
                proc.setProcessado(false);
            }
            if("I/O-Bound(Fita)".equals(proc.getTipo()))
            {
                Thread.sleep(500);
                proc.setProcessado(false);
            }
            
            TrocaEstado(proc, "Ponto");
            System.out.println(proc.toString());
            if(!proc.finaliza)
            {
                listRun.add(proc);
            }
            else
            {
                Temp.FinalizaProcesso(proc.getPid());
            }
            

        } 
    }
    
    public void TrocaEstado(Processo proc, String estado)
    {
        Temp.AtualizaEstado(proc.getPid(), estado);
    }
    
    public void AtualizaListas()
    {
        if(Temp.list.size() > 0)
        {
            for (Processo p : Temp.list) {
                AtualizaFinalizar(p.getPid(), p.finaliza);
            }
        }
    }

    public void VerificaProcessoNovo()
    {
        if(Temp.list.size() != listRun.size() && Temp.list.size() > 0)
        {
            if(Temp.list.size() > listRun.size())
            {
                for (Processo proc : Temp.list) {
                    if("N/A".equals(proc.getEstado()))
                    {
                        listRun.add(proc);
                        Temp.AtualizaEstado(proc.getPid(), "Ponto");
                    }
                }
            }
        }
    }
    public void AtualizaFinalizar(int pid, boolean finalizar)
    {
        Processo returnProc = ReturnaProcessoPorPid(pid);  
        
        int index = listRun.indexOf(returnProc);
        returnProc.finaliza = finalizar;
        
        listRun.set(index, returnProc);
    }
    
    
    public Processo ReturnaProcessoPorPid(int pid)
    {
        Processo returnProc = null;
        for (Processo proc : listRun) {
            if(proc.getPid() == pid)
            {
                returnProc = proc;
            }
        }

        if(returnProc == null)
        {
            throw new ArrayIndexOutOfBoundsException("Pid não encontado");
        }
        else
        {
            return returnProc;
        }        
    }     
    
    public void AtualizaPrioridade(int pid, int prioridade)
    {
        int index;
        Processo returnProc = ReturnaProcessoPorPid(pid);  
        
        index = listRun.indexOf(returnProc);
        returnProc.setPrioridade(prioridade);
        
        listRun.set(index, returnProc);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
