
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import model.Processo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jeisonmarques
 */
public class GerenciaDeProcessos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerenciaDeProcessos
     */
    public GerenciaDeProcessos() {
        initComponents();
        
         Timer timer = new Timer();
    
     timer.scheduleAtFixedRate(new TimerTask() {
     int t=0;
     public void run() {
            if(t>100)
              t = 0;
            else
              t++;
            
            Popula();
            //jProgressBar.setValue(t);
            Date d = new Date();
            System.out.println("Tela grid atualizada as " + d.toString());
            //jLabelVelocidade.setText(""+ jSlider.getValue());
       }
    }, 0, 1000);
    }

    public void deletaTodasLinhas(final DefaultTableModel model) {
    for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
        model.removeRow(i);
        }
    }
    public void Popula()
    {
        DefaultTableModel modelo = (DefaultTableModel) jTableProcesso.getModel();
        deletaTodasLinhas(modelo);
        for (Processo val : Temp.list) {
            modelo.addRow(new String [] {""+val.getPid(),val.getEstado(), ""+val.getTempoProcessamento()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSuspender = new javax.swing.JButton();
        jButtonProsseguir = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonPrioridade = new javax.swing.JButton();
        jButtonCriar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProcesso = new javax.swing.JTable();

        jButtonSuspender.setText("Suspender");

        jButtonProsseguir.setText("Prosseguir");

        jButtonFinalizar.setText("Finalizar");

        jButtonPrioridade.setText("Prioridade");

        jButtonCriar.setText("Criar");
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });

        jTableProcesso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Estado", "Tempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProcesso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonProsseguir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonFinalizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrioridade, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonCriar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSuspender, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCriar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSuspender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonProsseguir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrioridade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        JDesktopPane desk = this.getDesktopPane();
        AddProcessos add = new AddProcessos();
        desk.add(add);
        add.setVisible(true); 
    }//GEN-LAST:event_jButtonCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonPrioridade;
    private javax.swing.JButton jButtonProsseguir;
    private javax.swing.JButton jButtonSuspender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProcesso;
    // End of variables declaration//GEN-END:variables
}
