
import ui.ProcessamentoUI;
import ui.LogDeProcessos;
import ui.GerenciaDeProcessos;
import ui.AddProcessos;
import util.Log;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jeisonmarques
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public AddProcessos view;
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(800, 600);

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTeste = new javax.swing.JMenu();
        jMenuItemGerenciaDeProcesso = new javax.swing.JMenuItem();
        jMenuItemLog = new javax.swing.JMenuItem();
        jMenuItemProcessamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktop.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jMenuTeste.setText("File");

        jMenuItemGerenciaDeProcesso.setText("Gerencia de Processos");
        jMenuItemGerenciaDeProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciaDeProcessoActionPerformed(evt);
            }
        });
        jMenuTeste.add(jMenuItemGerenciaDeProcesso);

        jMenuItemLog.setText("Log de Processos");
        jMenuItemLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogActionPerformed(evt);
            }
        });
        jMenuTeste.add(jMenuItemLog);

        jMenuItemProcessamento.setText("Processamento");
        jMenuItemProcessamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProcessamentoActionPerformed(evt);
            }
        });
        jMenuTeste.add(jMenuItemProcessamento);

        jMenuBar1.add(jMenuTeste);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGerenciaDeProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciaDeProcessoActionPerformed
        GerenciaDeProcessos ger = new GerenciaDeProcessos();
        ger.setVisible(true);
        jDesktop.add(ger);
    }//GEN-LAST:event_jMenuItemGerenciaDeProcessoActionPerformed

    private void jMenuItemLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogActionPerformed
        LogDeProcessos log = new LogDeProcessos();
        log.setVisible(true);
        jDesktop.add(log);
    }//GEN-LAST:event_jMenuItemLogActionPerformed

    private void jMenuItemProcessamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProcessamentoActionPerformed
        ProcessamentoUI proc = new ProcessamentoUI();
        proc.setVisible(true);
        jDesktop.add(proc);
    }//GEN-LAST:event_jMenuItemProcessamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemGerenciaDeProcesso;
    private javax.swing.JMenuItem jMenuItemLog;
    private javax.swing.JMenuItem jMenuItemProcessamento;
    private javax.swing.JMenu jMenuTeste;
    // End of variables declaration//GEN-END:variables
}
